# production environment
FROM nginx:latest
RUN apt install -y gettext-base
COPY build/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/nginx.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;"]