export const routes = {
  ROLE_MANAGEMENT: "/roleManagement",
  HOME: "/home",
  DATA_LOAD: "/dataLoad",
  DEMAND_PLANNING_DASHBOARD: "/demandPlanning",
  FORECAST_SELECTION: "/forecastSelection",
  FORECAST_SELECTION_VARIANTS: "/forecastModelVariants",
  FORECAST_EXECUTION: "/forecastExecution",
  FORECAST_EXECUTION_VARIANTS: "/forecastExecutionVariants",
  FORECAST_PROFILE: "/forecastProfile",
  PRODUCT_ACTIVATION: "/productActivation",
  PRODUCT_POOL_ASSIGNMENT: "/assignProductPool",
  PROFILE_MANAGEMENT: "/profile",
  SCHEDULER: "/scheduler",
  TABLE_VIEW: "/viewTables",
  USER_MANAGEMENT: "/userManagement",
  VARIANT: "/variants",
  FORGOT_PASSWORD: "/forgotPassword",
  RESET_PASSWORD: "/resetPassword",
  WELCOME: "/welcome",
  SIGNIN: "/signin",
  NOT_FOUND: "/not-found",
  HELP: "/help",
  DB_CONNECTION: "/dbConnection",
  MANAGE_CONNECTION: "/databaseConnection",
  API_CREDENTIALS: "/exposedAPIs",
  LOGIN: "/login",
  DATA_MAPPING: "/dataMapping",
  DATA_MAPPING_LIST: "/showDataMapping",
};

export const menuRouteLabels = {
  ROLE_MANAGEMENT: "Role Management",
  HOME: "Home",
  DATA_LOAD: "Data Load",
  DEMAND_PLANNING: "Demand Planning",
  DEMAND_PLANNING_DASHBOARD: "Dashboard",
  FORECAST_SELECTION_VARIANTS: "Forecast Assignment",
  FORECAST_EXECUTION_VARIANTS: "Forecast Execution",
  FORECAST_PROFILE: "Forecast Profiles",
  PRODUCT_ACTIVATION: "Licensing",
  PRODUCT_POOL_ASSIGNMENT: "Assign Product Pool",
  PROFILE_MANAGEMENT: "User Profile",
  SCHEDULER: "Scheduler",
  TABLE_VIEW: "Table Views",
  USER_MANAGEMENT: "User Management",
  VARIANT: "Variants",
  HELP: "Help",
  DB_CONNECTION: "Connect To Database",
  MANAGE_CONNECTION: "Manage Connections",
  DATA_MAPPING: "Data Mapping",
  DATA_MAPPING_LIST: "Show Data Mapping",
  API_CREDENTIALS: "Api Credentials",
};
